### ISSUE TITLE
ProductManager endpoints

### ISSUE THREAD

**Issue by ryanfreeth** [iQmetrix/SampleApplications#13]
This is more of an FYI but we do not promise backwards compatibility on `/productmanager/` endpoints.
You are using it here to set the Hero Shot https://github.com/iQmetrix/SampleApplications/blob/master/Magento/Utilities/UrlFormatter.cs#L482

When creating a Master Product the first asset it automatically set as the Hero Shot.

**Comment by melissakendall** [comment]
noted, I'll change it
